### ISSUE TITLE
Popular course card broke when description is too long

### ISSUE THREAD

**Issue by khajornritdacha** [thinc-org/hacktoschool-fryingchicken#27]
https://github.com/thinc-org/hacktoschool-fryingchicken/blob/f1335661434a155a4c79f7e8d8efe3d630d20895/frontend/components/LandingPage/ThirdComponent.tsx#L30

It probably is a CSS problem, but I currently do not know how to fix it.

**Comment by Nacnano** [comment]
Fixed in [#36](https://github.com/thinc-org/hacktoschool-fryingchicken/pull/36)

Closing na
